# Generated by Django 6.0.1 on 2026-02-05 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Unna Model', max_length=100)),
                ('description', models.CharField(help_text='Short description', max_length=80)),
                ('image_url', models.URLField(help_text='Direct link to photo')),
                ('details_link', models.URLField(help_text='Link to property page')),
                ('total_contract_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('downpayment_percent', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('loan_term_years', models.IntegerField(default=20)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=7.0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psid', models.CharField(max_length=100, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('COLD', 'Inquirer'), ('WARM', 'Interested'), ('HOT', 'Hot Lead')], default='COLD', max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('current_step', models.CharField(choices=[('START', 'Starting'), ('ASKED_BUDGET', 'Asked Budget'), ('ASKED_LOCATION', 'Asked Location'), ('ASKED_FINANCING', 'Asked Financing'), ('ASKED_PHONE', 'Asked Phone'), ('COMPLETED', 'Completed')], default='START', max_length=50)),
                ('financing_type', models.CharField(blank=True, choices=[('BANK', 'Bank'), ('CASH', 'Cash'), ('PAGIBIG', 'Pag-IBIG')], max_length=20, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=50, null=True)),
                ('location_pref', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interested_house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_engine.housemodel')),
            ],
        ),
    ]
