# Generated by Django 6.0.1 on 2026-02-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='timeline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
