# Generated by Django 6.0.1 on 2026-02-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0002_lead_timeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='location',
            field=models.CharField(choices=[('Magalang', 'Magalang, Pampanga'), ('Tanza', 'Tanza, Cavite'), ('GenTri', 'General Trias, Cavite')], default='Magalang', max_length=100),
        ),
    ]
