# Generated by Django 6.0.1 on 2026-02-10 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0003_housemodel_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Feb-IBIG Month Promo', max_length=200)),
                ('description', models.TextField(help_text='e.g. Less 120k upon reservation!')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_houses', models.ManyToManyField(related_name='promos', to='bot_engine.housemodel')),
            ],
        ),
    ]
