# Generated by Django 6.0.1 on 2026-02-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0004_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='reservation_fee',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='total_contract_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='promo',
            name='applicable_houses',
            field=models.ManyToManyField(blank=True, related_name='promos', to='bot_engine.housemodel'),
        ),
    ]
