# Generated by Django 6.0.1 on 2026-02-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0005_housemodel_reservation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='pagibig_downpayment_percent',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=5, verbose_name='Pag-IBIG DP % (15 or 20)'),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='downpayment_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Bank DP %'),
        ),
    ]
