# Generated by Django 6.0.1 on 2026-02-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0006_housemodel_pagibig_downpayment_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='cash_discount_percent',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=5, verbose_name='Cash Discount %(8)'),
        ),
    ]
