# Generated by Django 6.0.1 on 2026-02-15 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0007_housemodel_cash_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='last_alert_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
