# Generated by Django 6.0.1 on 2026-02-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0008_lead_last_alert_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='followed_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
