# Generated by Django 6.0.1 on 2026-02-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0009_lead_followed_up_lead_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='Public URL (e.g., from Imgur or Cloudinary)', max_length=500)),
                ('category', models.CharField(choices=[('TURNOVER', 'Turnover / Deliverable Unit'), ('DRESSED', 'Dressed-up / Model Unit')], max_length=20)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bot_engine.housemodel')),
            ],
        ),
    ]
