# Generated by Django 6.0.1 on 2026-02-22 10:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0010_houseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='bank_interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Bank annual interest rate in percent (e.g., 8.00 for 8%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='housemodel',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.00'), help_text='Pag-IBIG annual interest rate in percent (e.g., 9.00 for 9%)', max_digits=5),
        ),
    ]
