# Generated by Django 6.0.1 on 2026-02-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0011_housemodel_bank_interest_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemodel',
            name='loan_term_years',
        ),
    ]
