# Generated by Django 6.0.1 on 2026-02-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0012_remove_housemodel_loan_term_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemodel',
            name='dressed_gallery_link',
            field=models.URLField(blank=True, help_text='Link to the full FB album for Dressed/Model units', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='turnover_gallery_link',
            field=models.URLField(blank=True, help_text='Link to the full FB album for Turnover/Bare units', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='housemodel',
            name='virtual_tour_link',
            field=models.URLField(blank=True, help_text='Link to the Facebook or YouTube virtual tour video', max_length=500, null=True),
        ),
    ]
